// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFejU5WwJHjX359QpnBF_OG4pX_eMtM0s',
    appId: '1:981708519357:web:ef9b0c43ea59c3496284d4',
    messagingSenderId: '981708519357',
    projectId: 'todomanagement-e07d8',
    authDomain: 'todomanagement-e07d8.firebaseapp.com',
    storageBucket: 'todomanagement-e07d8.firebasestorage.app',
    measurementId: 'G-N25V6KYHNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_IpuytZh9Mv1AQr7qrKWRSGGsx51qdmA',
    appId: '1:981708519357:android:e8bd2e7ada19476e6284d4',
    messagingSenderId: '981708519357',
    projectId: 'todomanagement-e07d8',
    storageBucket: 'todomanagement-e07d8.firebasestorage.app',
  );
}
